name: Test Actions

on: 
  workflow_dispatch:  # manually
  push:
    branches: [ $default-branch, main, master ]

permissions:
  contents: read

jobs:
  #call-workflow-test-slack-fail-alert:
  #  uses: ./.github/workflows/test-slack-fail-alert.yaml  
  call-workflow-test-aws-login:
    uses: ./.github/workflows/test-aws-login.yaml  
    permissions:
      contents: read
      id-token: write
  call-workflow-test-elk-docker-build-cache-push:
    uses: ./.github/workflows/test-elk-docker-build-cache-push.yaml  
    permissions:
      contents: write
      id-token: write
  call-workflow-test-elk-dynamic-input-defaults:
    uses: ./.github/workflows/test-elk-dynamic-input-defaults.yaml  
  call-workflow-test-build-tag-number:
    uses: ./.github/workflows/test-build-tag-number.yaml
    permissions:
      contents: write
  call-workflow-test-upload-s3:
    uses: ./.github/workflows/test-upload-s3.yaml
    permissions:
      contents: read
      id-token: write
  call-workflow-test-elk-tag-and-release:
    uses: ./.github/workflows/test-elk-tag-and-release.yaml
    permissions:
      contents: write

