name: Test login to AWS

on: workflow_dispatch

permissions:
  contents: read
  id-token: write

jobs:
  upload-s3-test-dir:
    name: Uploads test directory to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Log in to AWS
        uses: elk-audio/.github/.github/actions/elk-aws-login@main

