name: Test build tag number

on: 
  workflow_dispatch:  # manually
  workflow_call:

permissions:
  contents: write

jobs:
  send-slack-failure-alert:
    name: Generate a build number
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build number
        uses: elk-audio/.github/.github/actions/build-tag-number@main
        with: 
          prefix: "test"
