name: Test Docker Build Cache Push

on: 
  workflow_call:
  workflow_dispatch:  # manually
    inputs:
        debug_enabled:
          type: boolean
          description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
          required: false
          default: false

permissions:
  contents: write
  id-token: write

jobs:
  build-and-push-docker-image:
    name: Build a test Docker image and push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - name: Build image and push to ECR
        uses: ./.github/actions/elk-docker-build-cache-push
        with:
          image-name: "test-elk-docker-build-cache-push"
          context: "./test-elk-docker-build-cache-push"
          extra-tags: "extra-tag"


