name: Test send a failure message to slack

on: 
  workflow_dispatch  # manually
  workflow_call

permissions:
  contents: read

jobs:
  send-slack-failure-alert:
    name: Send Slack Failure Alert
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send slack failure alert
        uses: ./.github/actions/slack-fail-alert
        #if: ${{ failure() && github.event_name != 'workflow_dispatch' }}
