
name: Test build tag number

on: 
  workflow_dispatch:  # manually
  workflow_call:

permissions:
  contents: read

jobs:
  send-slack-failure-alert:
    name: Send Slack Failure Alert
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build number
        id: build-number
        prefix: test
        uses: elk-audio/.github/.github/actions/build-tag-number@main
